#!/bin/bash

set -euo pipefail

cd $(dirname $BASH_SOURCE)

docker build -t trackwarrior .

docker run --rm \
  -it \
  -v "/etc/timezone:/etc/timezone:ro" \
  -v "/etc/localtime:/etc/localtime:ro" \
  -v "$HOME/.trackwarrior-docker:/root" \
  trackwarrior:latest
